### ISSUE TITLE
API breaks when current locale uses a different decimal separator

### ISSUE THREAD

**Issue by tobias2k** [guhelski/forecast-php#5]
The code that composes a request uses string concatenation to interpolate latitude and longitude into a URL. This triggers a conversion to string, which, for numeric values, uses the current locale. If the locale is something like `nl_NL`, which uses `','` as the decimal separator rather than `'.'`, then so will the resulting URL. The Forecast API, however, expect the dot character, always, so this produces an error.

On a side note, there is also a security implication here; I'll be happy to explain in private if you prefer.

**Comment by guhelski** [comment]
I'll be happy to hear about the security implication and maybe your suggestion on how to fix it, should we make sure the decimal separator is a dot instead of a comma on the latitude and longitude values independent of locale? Type cast them?

**Comment by tobias2k** [comment]
Functionally speaking, explicitly forcing the decimal separator to a
dot, and avoiding any other locale-specific formatting, is probably the
way to go; what I would do is force the type to float (by casting), then
explicitly formatting the number with a decimal dot.

Regarding the security implications, would you like to discuss this via
a private channel? If so, my e-mail address is tobias@twokings.nl, and
my GPG key is attached (not sure if github supports this though ;).

On Thu, Jan 29, 2015 at 02:51:31PM -0800, Guilherme Uhelski wrote:
> I'll be happy to hear about the security implication and maybe your
> suggestion on how to fix it, should we make sure the decimal separator
> is a dot instead of a comma on the latitude and longitude values
> independent of locale? Type cast them?
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/guhelski/forecast-php/issues/5#issuecomment-72120821

-- 
Tobias Dammers - tobias@twokings.nl - 070-3457628 - www.twokings.nl
Maandag t/m donderdag van 9.00 tot 17.30
Voor dringende vragen, mail naar support@twokings.nl
